version: "3.9"
services:
  traffic-app:
    build: .
    container_name: traffic-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./traffic_data:/app/traffic_data
      - ./traffic_csv:/app/traffic_csv