version: "3.9"
services:
  traffic-app:
    build: .
    container_name: traffic-app
    ports:
      - "8080:8080"
    env_file:
      - spring-boot-server/.env
    volumes:
      - ./spring-boot-server/traffic_data:/app/traffic_data
      - ./spring-boot-server/traffic_csv:/app/traffic_csv